### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by postadelmaga** [kasti0/Hackintosh_Lenovo-IdeaPad-330s-15ikb#5]
I am preparing a OC folder for this pc for a friend.
If you are interested I can share it so you can add it to the repo.

**Comment by kasti0** [comment]
My laptop is working with zero known issues. The purpose of this repo is not to provide a full EFI because it would be outdated soon and people won’t learn anything if I just provide my pre-built EFI. Read the guides linked in my repo then you can do it yourself, learn something and you’ll be able to troubleshoot when something breaks. Only files provided in my repo are SSDTs I wrote myself that fix issues specific to this model.

**Comment by postadelmaga** [comment]
ok cool.
I just followed opencore guide for coffee lake, it just very boring ... I don't think I learned anything interesting since I just want to use logic ... but I understand everyone has it's own opinion about that.
Thanks for your repo :)
